Minor adjustments, see individual commits
GeoScripting-WUR/RProjectManagement pull request #27
Opened 2022-11-24 09:51 UTC by mvansluijs

2022-11-28 10:31 UTC, mvansluijs commented
@GreatEmerald

2022-11-28 18:56 UTC, GreatEmerald requested changes
Thanks, a few comments.

2022-11-28 18:56 UTC, GreatEmerald commented on index.Rmd
> +Welcome to the Geoscripting course! Today we will get familiar with Linux, which is an advanced environment optimized for scripting, and with version control software that helps you collaborate with
Again, "optimised" is the correct British spelling.

2022-11-28 18:56 UTC, GreatEmerald commented on index.Rmd
> +**In case you can't get the VDI running successfully** (and **only** in that case, so hopefully you don't need to do this!), there is an alternative: we have the possibility of providing access to a
SURF Research Cloud x2

2022-11-28 18:56 UTC, GreatEmerald commented on index.Rmd
> -Once you have everything ready, login into your Linux VM, try out RStudio/RKWard, and also open QGIS. Explore the environment a little to get used to it.
It's a good idea to also check out RKWard, it should be installed.

2022-11-29 10:23 UTC, mvansluijs commented on index.Rmd
> -Once you have everything ready, login into your Linux VM, try out RStudio/RKWard, and also open QGIS. Explore the environment a little to get used to it.
It is shown twice in the applications overview actually. I'm not good enough with Linux to be able to tell whether this means that it is installed twice or somehow linked twice. Seems to work properly on both SURF and VMWARE VMs.

2022-12-01 17:08 UTC, GreatEmerald commented on index.Rmd
> -Once you have everything ready, login into your Linux VM, try out RStudio/RKWard, and also open QGIS. Explore the environment a little to get used to it.
Yes, that's just because it ships two startup files, but it's not a problem.

2022-12-02 13:18 UTC, mvansluijs commented on index.Rmd
> -Once you have everything ready, login into your Linux VM, try out RStudio/RKWard, and also open QGIS. Explore the environment a little to get used to it.
Then I think this one is ready to be merged (?)

2022-12-02 13:33 UTC, GreatEmerald commented on index.Rmd
> -Once you have everything ready, login into your Linux VM, try out RStudio/RKWard, and also open QGIS. Explore the environment a little to get used to it.
You should still keep the mention of RKWard there, that was the point of this comment :)

2022-12-02 14:15 UTC, mvansluijs commented on index.Rmd
> -Once you have everything ready, login into your Linux VM, try out RStudio/RKWard, and also open QGIS. Explore the environment a little to get used to it.
Ah whoops haha

2022-12-02 14:16 UTC, mvansluijs commented on index.Rmd
> -Once you have everything ready, login into your Linux VM, try out RStudio/RKWard, and also open QGIS. Explore the environment a little to get used to it.
It's in again

2022-12-02 14:31 UTC, GreatEmerald approved these changes
Thanks!

2022-12-02 14:31 UTC, merged